packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild

allowBuilds:
  '@parcel/watcher': true
  esbuild: false
  unrs-resolver: false

minimumReleaseAgeExclude:
  - genericsuite-be-scripts@1.4.0
