components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    MenuElementRequest:
      description: 'Menu element request '
      properties:
        element:
          title: Element
          type: string
      required:
      - element
      title: MenuElementRequest
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
  securitySchemes:
    HTTPBasic:
      scheme: basic
      type: http
info:
  title: fastapitemplate-backend
  version: 0.1.0
openapi: 3.1.0
paths:
  /v1/assets/:
    get:
      description: Get authorized menu options
      operationId: storage_retrieval_no_item_id_endpoint_v1_assets__get
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Storage Retrieval No Item Id Endpoint V1 Assets  Get
          description: Successful Response
      summary: Storage Retrieval No Item Id Endpoint
  /v1/assets/{item_id}:
    get:
      description: Get authorized menu options
      operationId: storage_retrieval_endpoint_v1_assets__item_id__get
      parameters:
      - in: path
        name: item_id
        required: true
        schema:
          title: Item Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Storage Retrieval Endpoint V1 Assets  Item Id  Get
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Storage Retrieval Endpoint
  /v1/assets/{item_id}/{response_type}:
    get:
      description: Get authorized menu options
      operationId: storage_retrieval_with_response_type_endpoint_v1_assets__item_id___response_type__get
      parameters:
      - in: path
        name: item_id
        required: true
        schema:
          title: Item Id
          type: string
      - in: path
        name: response_type
        required: true
        schema:
          title: Response Type
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Storage Retrieval With Response Type Endpoint V1 Assets  Item
                  Id   Response Type  Get
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Storage Retrieval With Response Type Endpoint
  /v1/menu_options:
    get:
      description: Get authorized menu options
      operationId: menu_options_get_v1_menu_options_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Menu Options Get
  /v1/menu_options/element:
    post:
      description: Get menu element configuration
      operationId: menu_options_element_v1_menu_options_element_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuElementRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Menu Options Element
      tags:
      - element
  /v1/users/current_user_d:
    get:
      description: Current user data read
      operationId: current_user_d_v1_users_current_user_d_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Current User D
  /v1/users/login:
    post:
      description: User login
      operationId: login_user_v1_users_login_post
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      security:
      - HTTPBasic: []
      summary: Login User
      tags:
      - login
  /v1/users/supad-create:
    post:
      description: Super admin user creation
      operationId: super_admin_create_v1_users_supad_create_post
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      security:
      - HTTPBasic: []
      summary: Super Admin Create
      tags:
      - super-admin
  /v1/users/test:
    get:
      description: Connection handler test
      operationId: test_connection_handler_v1_users_test_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Test Connection Handler
      tags:
      - test
