# deploy/docker_images/Dockerfile-Python

FROM python:3.12-slim

EXPOSE 8000 8070

# Set working directory
WORKDIR /code

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    build-essential \
    pipx \
    && rm -rf /var/lib/apt/lists/*

#  Finish pipx installation
RUN pipx ensurepath

# Install Poetry
RUN pipx install poetry

RUN pip install --upgrade pip && pip install --no-cache-dir \
    "fastapi>=0.121.3,<0.122.0" \
    "fastapi-cors>=0.0.6,<0.0.7" \
    "genericsuite>=0.2.0,<0.3.0" \
    "genericsuite-ai>=0.2.0,<0.3.0" \
    "mangum>=0.19.0,<0.20.0" \
    "python-multipart>=0.0.20,<0.0.21" \
    "uvicorn[standard]>=0.38.0,<0.39.0"

